# Project-Manager mode
* Header 							   :noexport:
:PROPERTIES:
#+TITLE: An emacs-org project manager for applied statisticians
#+EMAIL: tag@biostat.ku.dk
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc author:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\usepackage[T1]{fontenc}
#+LaTeX_HEADER:\renewcommand*\familydefault{\sfdefault}
#+LaTeX_HEADER:\usepackage[table,usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER:\definecolor{lightGray}{gray}{0.98}
#+LaTeX_HEADER:\definecolor{medioGray}{gray}{0.83}
#+LaTeX_HEADER:\rowcolors{1}{medioGray}{lightGray}
#+LaTeX_HEADER:\usepackage{attachfile}
#+LaTeX_HEADER:\usepackage{array}
#+LaTeX_HEADER:\author{Thomas Alexander Gerds}
#+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen, Denmark}
#+LaTeX_HEADER:\author{Klaus K\"ahler Holst}
#+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen, Denmark}
#+LaTeX_HEADER:\author{Jochen Knaus}
#+LaTeX_HEADER:\affil{Department of Medical Biometrie and Medical Informatics, University of Freiburg, Freiburg, Germany}
#+LaTeX_HEADER:\newcommand{\sfootnote}[1]{\renewcommand{\thefootnote}{\fnsymbol{footnote}}\footnote{#1}\setcounter{footnote}{0}\renewcommand{\thefootnote}{\arabic{foot note}}}
#+LaTeX_HEADER:\makeatletter\def\blfootnote{\xdef\@thefnmark{}\@footnotetext}\makeatother
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LaTeX_HEADER \itemsep2pt
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+LaTeX_HEADER: \usepackage{color}
#+LATEX_HEADER: \lstset{
#+LATEX_HEADER: keywordstyle=\color{blue},
#+LATEX_HEADER: commentstyle=\color{red},
#+LATEX_HEADER: stringstyle=\color[rgb]{0,.5,0},
#+LATEX_HEADER: basicstyle=\ttfamily\small,
#+LATEX_HEADER: columns=fullflexible,
#+LATEX_HEADER: breaklines=true,        % sets automatic line breaking
#+LATEX_HEADER: breakatwhitespace=false,    % sets if automatic breaks should only happen at whitespace
#+LATEX_HEADER: numbers=left,
#+LATEX_HEADER: numberstyle=\ttfamily\tiny\color{gray},
#+LATEX_HEADER: stepnumber=1,
#+LATEX_HEADER: numbersep=10pt,
#+LATEX_HEADER: backgroundcolor=\color{white},
#+LATEX_HEADER: tabsize=4,
#+LATEX_HEADER: showspaces=false,
#+LATEX_HEADER: showstringspaces=false,
#+LATEX_HEADER: xleftmargin=.23in,
#+LATEX_HEADER: frame=single,
#+LATEX_HEADER: basewidth={0.5em,0.4em}
#+LATEX_HEADER: }
#+PROPERTY: session *R* 
#+PROPERTY: cache yes
#+PROPERTY: tangle yes
#+PROPERTY: colnames yes
:END:
  
* Introduction 
  
  This document simulaneously describes and defines a project manager
  for applied statistical workflows based on the fabulous and popular
  emacs =org-mode=. Really it describes and automates one out of many
  possibilities to customize =org-mode=.
  
** Getting started
   
   The first thing to do is to define some new projects. Obviously,
   you would rather read in your existing projects. Don't worry, 
   this is also possible and explained below.
   
*** The project manager file
    
#+BEGIN_SRC emacs-lisp :exports none :eval never :tangle no
  (setq org-pro-file "~/projects/manager.org")
  (find-file org-pro-file)
#+END_SRC

**** What is a project?
    
     As in real life, a project can be many different things. The
     prototype project consists of a /location/, that is a directory
     on your computer, and an index file. (Actually, only one of
     /index/ and /location/ is required.)
     
**** How to define a project?
     
     Projects are defined in the file /org-pro-file/
     (yes-you-need-to-create-this-file) in the following format.
     
#+BEGIN_SRC org :tangle no
 * Cat 1
 ** Subcat 1
 *** Subsubcat 1
 **** Learning org (My first org-pro project)
 :PROPERTIES:
 :NICKNAME: howto-org
 :INDEX:  ~/knowhow/howto.org
 :LOCATION: ~/knowhow/
 :OTHERS: justme
 :END:     
 **** Test org-pro
 :PROPERTIES:
 :NICKNAME: howto-org
 :INDEX:  ~/knowhow/howto.org
 :LOCATION: ~/knowhow/
 :OTHERS: Alphonse Quack
 :END:     
#+END_SRC

** Git support
*** Requirements

You need to install the program git.

*** Git hub

To do push changes to a github repository it is useful to set up git  
https://help.github.com/articles/set-up-git
and to be free of typing the username and password when doing "git push".

If you use the SSH repo URL instead, SSH keys are used for
authentication. This guide offers help generating and using an SSH key
pair:  https://help.github.com/articles/generating-ssh-keys



*** View documents
Insert something like this in '* Documents' section (or globally)

#+BEGIN_EXAMPLE
#+COLUMNS: %20ITEM(Title) %8TODO(ToDo) %GitStatus %50LastCommit(Last Commit)
;; Default: %25ITEM %TODO %3PRIORITY %TAGS"
#+END_EXAMPLE

Right now we will set this globally. But it may be preferable to do
this on file basis - perhaps added to each property by the appropiate
capture mechanism.

** Window configuration
** Hacking deft
*** TODO Fix problems with local hash

To achieve multiple defts, we made variables deft-hash-* buffer
local. When a file is entered this way and then saved, a hook tries to
update the deft-hash-* tables. This does currently not work because
the variables are local to the *deft* buffer.



** Export
*** Publishing


